[0m18:20:18.909829 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108776a50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087cbf80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1087f0350>]}


============================== 18:20:18.910443 | d8575e04-525f-421a-9e7b-c22d73bf0cfd ==============================
[0m18:20:18.910443 [info ] [MainThread]: Running with dbt=1.8.1
[0m18:20:18.910732 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': '/Users/pcunha/Developement/Github/Data-Engineering-on-Azure/Dbt_Project/logs', 'profiles_dir': '/Users/pcunha/Developement/Github/Data-Engineering-on-Azure/Dbt_Project', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:20:18.920565 [info ] [MainThread]: dbt version: 1.8.1
[0m18:20:18.920768 [info ] [MainThread]: python version: 3.12.2
[0m18:20:18.920904 [info ] [MainThread]: python path: /Users/pcunha/miniconda3/bin/python
[0m18:20:18.921024 [info ] [MainThread]: os info: macOS-15.0-arm64-arm-64bit
[0m18:20:18.922557 [info ] [MainThread]: Using profiles dir at /Users/pcunha/Developement/Github/Data-Engineering-on-Azure/Dbt_Project
[0m18:20:18.922713 [info ] [MainThread]: Using profiles.yml file at /Users/pcunha/Developement/Github/Data-Engineering-on-Azure/Dbt_Project/profiles.yml
[0m18:20:18.922838 [info ] [MainThread]: Using dbt_project.yml file at /Users/pcunha/Developement/Github/Data-Engineering-on-Azure/Dbt_Project/dbt_project.yml
[0m18:20:18.977376 [info ] [MainThread]: Configuration:
[0m18:20:18.977670 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m18:20:18.977823 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m18:20:18.978016 [info ] [MainThread]: Required dependencies:
[0m18:20:18.978213 [debug] [MainThread]: Executing "git --help"
[0m18:20:18.992242 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m18:20:18.992854 [debug] [MainThread]: STDERR: "b''"
[0m18:20:18.993052 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m18:20:18.993220 [info ] [MainThread]: Connection test skipped since no profile was found
[0m18:20:18.993362 [info ] [MainThread]: [31m1 check failed:[0m
[0m18:20:18.993484 [info ] [MainThread]: Profile loading failed for the following reason:
Runtime Error
  Could not find profile named 'API_Footeball'


[0m18:20:19.002442 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.126473, "process_user_time": 0.566442, "process_kernel_time": 0.11966, "process_mem_max_rss": "95993856", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m18:20:19.002886 [debug] [MainThread]: Command `dbt debug` failed at 18:20:19.002824 after 0.13 seconds
[0m18:20:19.003167 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088029c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1070750d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108776a50>]}
[0m18:20:19.003413 [debug] [MainThread]: Flushing usage events
[0m18:21:36.793833 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1068340e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d0a2d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d846e0>]}


============================== 18:21:36.794615 | e804f01f-9525-4e4b-80aa-c1038a67feea ==============================
[0m18:21:36.794615 [info ] [MainThread]: Running with dbt=1.8.1
[0m18:21:36.795001 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/pcunha/Developement/Github/Data-Engineering-on-Azure/Dbt_Project', 'version_check': 'True', 'warn_error': 'None', 'log_path': '/Users/pcunha/Developement/Github/Data-Engineering-on-Azure/Dbt_Project/logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:21:36.803634 [info ] [MainThread]: dbt version: 1.8.1
[0m18:21:36.803876 [info ] [MainThread]: python version: 3.12.2
[0m18:21:36.804022 [info ] [MainThread]: python path: /Users/pcunha/miniconda3/bin/python
[0m18:21:36.804146 [info ] [MainThread]: os info: macOS-15.0-arm64-arm-64bit
[0m18:21:36.817702 [error] [MainThread]: Encountered an error:
dlopen(/Users/pcunha/miniconda3/lib/python3.12/site-packages/pyodbc.cpython-312-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/unixodbc/lib/libodbc.2.dylib
  Referenced from: <C7D1A9B0-FA23-3D45-96A4-AD2C7E7CDC9F> /Users/pcunha/miniconda3/lib/python3.12/site-packages/pyodbc.cpython-312-darwin.so
  Reason: tried: '/opt/homebrew/opt/unixodbc/lib/libodbc.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/unixodbc/lib/libodbc.2.dylib' (no such file), '/opt/homebrew/opt/unixodbc/lib/libodbc.2.dylib' (no such file)
[0m18:21:36.821500 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/cli/main.py", line 405, in debug
    results = task.run()
              ^^^^^^^^^^
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/task/debug.py", line 120, in run
    load_profile_status: SubtaskStatus = self._load_profile()
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/task/debug.py", line 211, in _load_profile
    profile: Profile = Profile.render(
                       ^^^^^^^^^^^^^^^
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/config/profile.py", line 403, in render
    return cls.from_raw_profiles(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/config/profile.py", line 369, in from_raw_profiles
    return cls.from_raw_profile_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/config/profile.py", line 325, in from_raw_profile_info
    credentials: Credentials = cls._credentials_from_profile(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/config/profile.py", line 149, in _credentials_from_profile
    cls = load_plugin(typename)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/adapters/factory.py", line 239, in load_plugin
    return FACTORY.load_plugin(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/adapters/factory.py", line 68, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcunha/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/adapters/fabric/__init__.py", line 3, in <module>
    from dbt.adapters.fabric.fabric_adapter import FabricAdapter
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/adapters/fabric/fabric_adapter.py", line 23, in <module>
    from dbt.adapters.fabric.fabric_connection_manager import FabricConnectionManager
  File "/Users/pcunha/miniconda3/lib/python3.12/site-packages/dbt/adapters/fabric/fabric_connection_manager.py", line 10, in <module>
    import pyodbc
ImportError: dlopen(/Users/pcunha/miniconda3/lib/python3.12/site-packages/pyodbc.cpython-312-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/unixodbc/lib/libodbc.2.dylib
  Referenced from: <C7D1A9B0-FA23-3D45-96A4-AD2C7E7CDC9F> /Users/pcunha/miniconda3/lib/python3.12/site-packages/pyodbc.cpython-312-darwin.so
  Reason: tried: '/opt/homebrew/opt/unixodbc/lib/libodbc.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/unixodbc/lib/libodbc.2.dylib' (no such file), '/opt/homebrew/opt/unixodbc/lib/libodbc.2.dylib' (no such file)

[0m18:21:36.825764 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.06461404, "process_user_time": 0.513173, "process_kernel_time": 0.108855, "process_mem_max_rss": "93044736", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m18:21:36.826216 [debug] [MainThread]: Command `dbt debug` failed at 18:21:36.826152 after 0.07 seconds
[0m18:21:36.826481 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10817ad80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1082fc6e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d0a0c0>]}
[0m18:21:36.826697 [debug] [MainThread]: Flushing usage events
